In [1]:
import pandas as pd
import os
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv(os.getcwd() + '/online_shoppers_intention 1.csv')
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [3]:
df.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')

In [4]:
df1 = df

In [5]:
# Drop the specified columns from df1
columns_to_drop = ['Month','TrafficType', 'VisitorType', 'Weekend', 'Revenue']
df1 = df1.drop(columns=columns_to_drop)

df1.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,1,1,1
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2,2,1
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,4,1,9
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,3,2,2
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,3,3,1

In [6]:
df1.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay',
       'OperatingSystems', 'Browser', 'Region'],
      dtype='object')

In [7]:
# Ensure all columns are numeric
numeric_cols = df1.select_dtypes(include=['number']).columns
df1_numeric = df1[numeric_cols]

# Normalize the numeric data
normalized_df = (df1_numeric - df1_numeric.min()) / (df1_numeric.max() - df1_numeric.min())

In [8]:
normalized_df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region
0,0.0,0.0,0.0,0.0,0.001418,0.000000,1.00,1.00,0.0,0.0,0.000000,0.000000,0.000
1,0.0,0.0,0.0,0.0,0.002837,0.001000,0.00,0.50,0.0,0.0,0.142857,0.083333,0.000
2,0.0,0.0,0.0,0.0,0.001418,0.000000,1.00,1.00,0.0,0.0,0.428571,0.000000,1.000
3,0.0,0.0,0.0,0.0,0.002837,0.000042,0.25,0.70,0.0,0.0,0.285714,0.083333,0.125
4,0.0,0.0,0.0,0.0,0.014184,0.009809,0.10,0.25,0.0,0.0,0.285714,0.166667,0.000

In [ ]:
# Sample 10% of the data
sampled_df = normalized_df.sample(frac=0.40, random_state=42)
#So please do not go over 0.3 for frac as this will EXPLODE the amount of time it takes to load.
sampled_df.shape

In [ ]:
import matplotlib.pyplot as plt
from sklearn.cluster import AffinityPropagation
from sklearn.decomposition import PCA

# Apply Affinity Propagation clustering to the sampled data
af = AffinityPropagation(random_state=42)
clusters = af.fit_predict(sampled_df)

# Reduce the dimensions of the sampled data for visualization using PCA
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(sampled_df)

# Plot the clusters
plt.figure(figsize=(10, 7))
plt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=clusters, cmap='rainbow', s=50)
plt.title('Affinity Propagation Clusters on Sampled Data')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.colorbar()
plt.show()

This one ABOVE uses the sample

In [ ]:
from sklearn.preprocessing import StandardScaler

# Normalize the data
scaler = StandardScaler()
df1_normalized = scaler.fit_transform(df1)

# Apply Affinity Propagation clustering to the normalized data
af_improved = AffinityPropagation(random_state=42)
clusters_improved = af_improved.fit_predict(df1_normalized)

# Reduce the dimensions of the normalized data for visualization using PCA
pca_improved = PCA(n_components=2)
reduced_data_improved = pca_improved.fit_transform(df1_normalized)

# Plot the clusters
plt.figure(figsize=(10, 7))
plt.scatter(reduced_data_improved[:, 0], reduced_data_improved[:, 1], c=clusters_improved, cmap='rainbow', s=50)
plt.title('Affinity Propagation Clusters on Normalized Data')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.colorbar()
plt.show()

In [ ]:
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Apply KMeans clustering to the entire normalized data
kmeans_normalized = KMeans(n_clusters=5, random_state=42)  # Assuming 5 clusters for demonstration
clusters_kmeans_normalized = kmeans_normalized.fit_predict(normalized_df)

# Reduce the dimensions for visualization using PCA
pca_kmeans_normalized = PCA(n_components=2)
reduced_data_kmeans_normalized = pca_kmeans_normalized.fit_transform(normalized_df)

# Plot the clusters for the entire normalized data using KMeans
plt.figure(figsize=(10, 7))
plt.scatter(reduced_data_kmeans_normalized[:, 0], reduced_data_kmeans_normalized[:, 1], c=clusters_kmeans_normalized, cmap='rainbow', s=50)
plt.title('KMeans Clusters on Normalized Data')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.colorbar()
plt.show()

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.cluster import AffinityPropagation
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

data = sampled_df

# Selecting only numerical columns
numerical_data = data.select_dtypes(include=['float64', 'int64'])

# Handling missing values
imputer = SimpleImputer(strategy='mean')
numerical_data_imputed = imputer.fit_transform(numerical_data)

# Scaling the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numerical_data_imputed)

# Applying Affinity Propagation clustering
af = AffinityPropagation(damping=0.5, max_iter=200, convergence_iter=15, preference=-50)
cluster_labels = af.fit_predict(scaled_data)

# Number of clusters formed
n_clusters = len(af.cluster_centers_indices_)
print(f"Number of clusters: {n_clusters}")

# Reduce dimensions using PCA
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(scaled_data)

# Scatter plot
plt.figure(figsize=(10, 7))
plt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=cluster_labels, cmap='rainbow', edgecolor='k')
plt.title('Clusters after Affinity Propagation')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.colorbar()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Reduce dimensions using PCA
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(sampled_df)

# Scatter plot
plt.figure(figsize=(10, 7))
plt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=cluster_labels, cmap='rainbow', edgecolor='k')
plt.title('Clusters after Affinity Propagation')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.colorbar()
plt.show()